sudo: required
dist: trusty
language: c

matrix:
 include:
  # OSX / Clang
  - os: osx
    osx_image: xcode8
  
  # Linux / GCC
  - os: linux
    compiler: gcc
    env: 
      - C_COMPILER=gcc-4.9
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: 
          - gcc-4.9
          - libreadline-dev
      
  - os: linux
    compiler: gcc
    env: 
      - C_COMPILER=gcc-5
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: 
          - gcc-5
          - libreadline-dev

  - os: linux
    compiler: gcc
    env:
      - C_COMPILER=gcc-6
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: 
          - gcc-6
          - libreadline-dev
  
before_script:
  - BUILD_DIR=$(pwd)/build
  - INSTALL_DIR=$BUILD_DIR/install

  - mkdir $BUILD_DIR
  - pushd $(pwd)
  - cd $BUILD_DIR

  - if [[ "${C_COMPILER}" != "" ]]; then export CMAKE_C_COMPILER=${C_COMPILER}; fi

  - cmake ../ -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR
  - cmake --build . --target install 

